# Course Handbook Configuration
#
# In this file you can customize your workshop website.
#
# Some defaults are set for a Galaxy-based workshop using GTN materials
# and an asynchronous format (video training sessions and support on chat)
title: Gallantries & GTN Training Library

# Training materials used. Defaults to GTN materials
materials:
  home: "https://training.galaxyproject.org/training-material/"
  url_prefix: "https://training.galaxyproject.org/training-material/"
  logo: "/assets/images/logos/Galaxy Training Network.png"


# Support platform defaults, can be overridden in training_sessions.yaml
support:
  platform: Slack
  link: "https://gtnsmrgsbord.slack.com/"
  join_link: "https://join.slack.com/t/gtnsmrgsbord/shared_invite/zt-x7vinbs1-BA~Kht6N86JBhDq0uTIVdQ"
  icebreaker_link: "https://gtnsmrgsbord.slack.com/archives/C01EDBVMHBQ"
  icebreaker_channel: "#social"
  feedback_link: "https://gtnsmrgsbord.slack.com/archives/C01NDF5SFH6"
  feedback_channel: "#feedback"

# videos
video:
  platform: YouTube
  url_prefix: "https://youtu.be/" # this will be prepended to the video ids you put in the schedule

# social
twitter_username: gxy-training
github_username:  shiltemann

# analytics
# will suffix analytics to any url to traning materials
# e.g. ?utm_source=galaxy-workshops&utm_medium=website&utm_campaign=my-workshop
analytics_source: "galaxy-workshop"
analytics_campaign: "galaxy-workshop"

# website configuration
baseurl: "/galaxy-workshop" # the subpath of your site. If you are serving this on github pages, it should be the same as your repository name.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_dir: /assets/images/
logo_dir: /assets/images/logos/
logo_dir_affil: /assets/images/institutions/


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

